// Shared TA vampire define pack.
// Loaded by TA_Vampires_include.dm before vampire override files.

#define THRALLS_METHUSELAH 69
#define THRALLS_ANCILLAE 20
#define THRALLS_NEONATE 5
#define THRALLS_THINBLOOD 1 // 0 - infinity. THINBLOOD can't convert anyway due the code.
#define THRALLS_DEFAULT 1


// CONVERT CONFIG
#define TA_VAMP_CONVERT_ANCILLAE_RESEARCH_COST 2
#define TA_VAMP_CONVERT_NEONATE_RESEARCH_COST 3
#define TA_VAMP_CONVERT_ANCILLAE_MAXBLOODPOOL_COST 250
#define TA_VAMP_CONVERT_NEONATE_MAXBLOODPOOL_COST 400
#define TA_VAMP_CONVERT_OFFER_RESEARCH_REWARD 1
#define TA_VAMP_CONVERT_OFFER_MAXBLOODPOOL_REWARD 500
#define TA_VAMP_DRAIN_RESEARCH_REWARD 1
#define TA_VAMP_DRAIN_MAXBLOODPOOL_REWARD 250
#define TA_VAMP_REFUSAL_RESEARCH_REWARD 1
#define TA_VAMP_REWARD_NEONATE_MAXBLOODPOOL_CAP 4000
#define TA_VAMP_REWARD_ANCILLAE_MAXBLOODPOOL_CAP 5000
#define TA_VAMP_CONVERT_PALLID_THRESHOLD 100
#define TA_VAMP_CONVERT_RESIST_STUN_TIME 1 MINUTES
#define TA_VAMP_DRAIN_MIN_BLOOD_VOLUME 230
#define TA_VAMP_DRAIN_STUN_TIME 1 MINUTES
#define TA_TRAIT_PALLID_DRAIN_IMMUNE "ta_pallid_drain_immune"
#define TA_TRAIT_PALLID_DRAINED_ONCE "ta_pallid_drained_once"
#define TA_VAMP_LETHAL_BLOODDRINK_DELAY 3 SECONDS
#define TA_VAMP_DIABLERIE_DELAY 10 SECONDS
#define TA_VAMP_DIABLERIE_RESEARCH_BONUS 1

// MASQUERADE CONFIG
#define MASQUERADE_COOLDOWN (5 MINUTES)

// TRANSFIX CONFIG
#define TA_TRANSFIX_MIN_MSG_LENGTH 50
#define TA_TRANSFIX_CHARS_PER_MINUTE 600
#define TA_TRANSFIX_PASTE_STUN_TIME 30 SECONDS
#define TA_TRANSFIX_PASTE_INT_LOSS 3
#define TA_TRANSFIX_PASTE_DEATH_INT 5
